/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { SimpleMultisig } from "./SimpleMultisig";
export type { SimpleMultisigFactory } from "./SimpleMultisigFactory";
