/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../common";

export interface SimpleMultisigInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "approveTransaction"
      | "executeTransaction"
      | "getBalance"
      | "getTransactionApprovals"
      | "proposeTransaction"
      | "signer1"
      | "signer2"
      | "signer3"
      | "transactionCount"
      | "transactions"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "TransactionApproved"
      | "TransactionExecuted"
      | "TransactionProposed"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "approveTransaction",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "executeTransaction",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getBalance",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getTransactionApprovals",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "proposeTransaction",
    values: [AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(functionFragment: "signer1", values?: undefined): string;
  encodeFunctionData(functionFragment: "signer2", values?: undefined): string;
  encodeFunctionData(functionFragment: "signer3", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "transactionCount",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "transactions",
    values: [BigNumberish]
  ): string;

  decodeFunctionResult(
    functionFragment: "approveTransaction",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "executeTransaction",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "getBalance", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getTransactionApprovals",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "proposeTransaction",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "signer1", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "signer2", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "signer3", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "transactionCount",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "transactions",
    data: BytesLike
  ): Result;
}

export namespace TransactionApprovedEvent {
  export type InputTuple = [transactionId: BigNumberish, signer: AddressLike];
  export type OutputTuple = [transactionId: bigint, signer: string];
  export interface OutputObject {
    transactionId: bigint;
    signer: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace TransactionExecutedEvent {
  export type InputTuple = [
    transactionId: BigNumberish,
    to: AddressLike,
    amount: BigNumberish
  ];
  export type OutputTuple = [transactionId: bigint, to: string, amount: bigint];
  export interface OutputObject {
    transactionId: bigint;
    to: string;
    amount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace TransactionProposedEvent {
  export type InputTuple = [
    transactionId: BigNumberish,
    to: AddressLike,
    amount: BigNumberish
  ];
  export type OutputTuple = [transactionId: bigint, to: string, amount: bigint];
  export interface OutputObject {
    transactionId: bigint;
    to: string;
    amount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface SimpleMultisig extends BaseContract {
  connect(runner?: ContractRunner | null): SimpleMultisig;
  waitForDeployment(): Promise<this>;

  interface: SimpleMultisigInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  approveTransaction: TypedContractMethod<
    [transactionId: BigNumberish],
    [void],
    "nonpayable"
  >;

  executeTransaction: TypedContractMethod<
    [transactionId: BigNumberish],
    [void],
    "nonpayable"
  >;

  getBalance: TypedContractMethod<[], [bigint], "view">;

  getTransactionApprovals: TypedContractMethod<
    [transactionId: BigNumberish],
    [[boolean, boolean, boolean]],
    "view"
  >;

  proposeTransaction: TypedContractMethod<
    [to: AddressLike, amount: BigNumberish],
    [void],
    "nonpayable"
  >;

  signer1: TypedContractMethod<[], [string], "view">;

  signer2: TypedContractMethod<[], [string], "view">;

  signer3: TypedContractMethod<[], [string], "view">;

  transactionCount: TypedContractMethod<[], [bigint], "view">;

  transactions: TypedContractMethod<
    [arg0: BigNumberish],
    [
      [string, bigint, boolean, boolean, boolean, boolean] & {
        to: string;
        amount: bigint;
        signer1Approved: boolean;
        signer2Approved: boolean;
        signer3Approved: boolean;
        executed: boolean;
      }
    ],
    "view"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "approveTransaction"
  ): TypedContractMethod<[transactionId: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "executeTransaction"
  ): TypedContractMethod<[transactionId: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "getBalance"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "getTransactionApprovals"
  ): TypedContractMethod<
    [transactionId: BigNumberish],
    [[boolean, boolean, boolean]],
    "view"
  >;
  getFunction(
    nameOrSignature: "proposeTransaction"
  ): TypedContractMethod<
    [to: AddressLike, amount: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "signer1"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "signer2"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "signer3"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "transactionCount"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "transactions"
  ): TypedContractMethod<
    [arg0: BigNumberish],
    [
      [string, bigint, boolean, boolean, boolean, boolean] & {
        to: string;
        amount: bigint;
        signer1Approved: boolean;
        signer2Approved: boolean;
        signer3Approved: boolean;
        executed: boolean;
      }
    ],
    "view"
  >;

  getEvent(
    key: "TransactionApproved"
  ): TypedContractEvent<
    TransactionApprovedEvent.InputTuple,
    TransactionApprovedEvent.OutputTuple,
    TransactionApprovedEvent.OutputObject
  >;
  getEvent(
    key: "TransactionExecuted"
  ): TypedContractEvent<
    TransactionExecutedEvent.InputTuple,
    TransactionExecutedEvent.OutputTuple,
    TransactionExecutedEvent.OutputObject
  >;
  getEvent(
    key: "TransactionProposed"
  ): TypedContractEvent<
    TransactionProposedEvent.InputTuple,
    TransactionProposedEvent.OutputTuple,
    TransactionProposedEvent.OutputObject
  >;

  filters: {
    "TransactionApproved(uint256,address)": TypedContractEvent<
      TransactionApprovedEvent.InputTuple,
      TransactionApprovedEvent.OutputTuple,
      TransactionApprovedEvent.OutputObject
    >;
    TransactionApproved: TypedContractEvent<
      TransactionApprovedEvent.InputTuple,
      TransactionApprovedEvent.OutputTuple,
      TransactionApprovedEvent.OutputObject
    >;

    "TransactionExecuted(uint256,address,uint256)": TypedContractEvent<
      TransactionExecutedEvent.InputTuple,
      TransactionExecutedEvent.OutputTuple,
      TransactionExecutedEvent.OutputObject
    >;
    TransactionExecuted: TypedContractEvent<
      TransactionExecutedEvent.InputTuple,
      TransactionExecutedEvent.OutputTuple,
      TransactionExecutedEvent.OutputObject
    >;

    "TransactionProposed(uint256,address,uint256)": TypedContractEvent<
      TransactionProposedEvent.InputTuple,
      TransactionProposedEvent.OutputTuple,
      TransactionProposedEvent.OutputObject
    >;
    TransactionProposed: TypedContractEvent<
      TransactionProposedEvent.InputTuple,
      TransactionProposedEvent.OutputTuple,
      TransactionProposedEvent.OutputObject
    >;
  };
}
