/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { SimpleMultisig__factory } from "./SimpleMultisig__factory";
export { SimpleMultisigFactory__factory } from "./SimpleMultisigFactory__factory";
