/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { Web3BridgeEmployees } from "./Web3BridgeEmployees";
export * as factories from "./factories";
export { Web3BridgeEmployees__factory } from "./factories/Web3BridgeEmployees__factory";
