/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedListener,
  TypedContractMethod,
} from "./common";

export declare namespace Web3BridgeEmployees {
  export type EmployeeStruct = {
    name: string;
    role: BigNumberish;
    employeeId: BigNumberish;
    isActive: boolean;
    hasAccess: boolean;
  };

  export type EmployeeStructOutput = [
    name: string,
    role: bigint,
    employeeId: bigint,
    isActive: boolean,
    hasAccess: boolean
  ] & {
    name: string;
    role: bigint;
    employeeId: bigint;
    isActive: boolean;
    hasAccess: boolean;
  };
}

export interface Web3BridgeEmployeesInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "addEmployee"
      | "employee"
      | "employees"
      | "getAllEmployees"
      | "getEmployee"
      | "grantAccess"
      | "updateEmployee"
  ): FunctionFragment;

  encodeFunctionData(
    functionFragment: "addEmployee",
    values: [AddressLike, string, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "employee",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "employees",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getAllEmployees",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getEmployee",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "grantAccess",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "updateEmployee",
    values: [AddressLike, BigNumberish, boolean, boolean]
  ): string;

  decodeFunctionResult(
    functionFragment: "addEmployee",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "employee", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "employees", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getAllEmployees",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getEmployee",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "grantAccess",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "updateEmployee",
    data: BytesLike
  ): Result;
}

export interface Web3BridgeEmployees extends BaseContract {
  connect(runner?: ContractRunner | null): Web3BridgeEmployees;
  waitForDeployment(): Promise<this>;

  interface: Web3BridgeEmployeesInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  addEmployee: TypedContractMethod<
    [_address: AddressLike, _name: string, _role: BigNumberish],
    [void],
    "nonpayable"
  >;

  employee: TypedContractMethod<
    [arg0: AddressLike],
    [
      [string, bigint, bigint, boolean, boolean] & {
        name: string;
        role: bigint;
        employeeId: bigint;
        isActive: boolean;
        hasAccess: boolean;
      }
    ],
    "view"
  >;

  employees: TypedContractMethod<
    [arg0: BigNumberish],
    [
      [string, bigint, bigint, boolean, boolean] & {
        name: string;
        role: bigint;
        employeeId: bigint;
        isActive: boolean;
        hasAccess: boolean;
      }
    ],
    "view"
  >;

  getAllEmployees: TypedContractMethod<
    [],
    [Web3BridgeEmployees.EmployeeStructOutput[]],
    "view"
  >;

  getEmployee: TypedContractMethod<
    [_address: AddressLike],
    [Web3BridgeEmployees.EmployeeStructOutput],
    "view"
  >;

  grantAccess: TypedContractMethod<[_address: AddressLike], [string], "view">;

  updateEmployee: TypedContractMethod<
    [
      _address: AddressLike,
      _role: BigNumberish,
      _isActive: boolean,
      _hasAccess: boolean
    ],
    [void],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "addEmployee"
  ): TypedContractMethod<
    [_address: AddressLike, _name: string, _role: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "employee"
  ): TypedContractMethod<
    [arg0: AddressLike],
    [
      [string, bigint, bigint, boolean, boolean] & {
        name: string;
        role: bigint;
        employeeId: bigint;
        isActive: boolean;
        hasAccess: boolean;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "employees"
  ): TypedContractMethod<
    [arg0: BigNumberish],
    [
      [string, bigint, bigint, boolean, boolean] & {
        name: string;
        role: bigint;
        employeeId: bigint;
        isActive: boolean;
        hasAccess: boolean;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "getAllEmployees"
  ): TypedContractMethod<
    [],
    [Web3BridgeEmployees.EmployeeStructOutput[]],
    "view"
  >;
  getFunction(
    nameOrSignature: "getEmployee"
  ): TypedContractMethod<
    [_address: AddressLike],
    [Web3BridgeEmployees.EmployeeStructOutput],
    "view"
  >;
  getFunction(
    nameOrSignature: "grantAccess"
  ): TypedContractMethod<[_address: AddressLike], [string], "view">;
  getFunction(
    nameOrSignature: "updateEmployee"
  ): TypedContractMethod<
    [
      _address: AddressLike,
      _role: BigNumberish,
      _isActive: boolean,
      _hasAccess: boolean
    ],
    [void],
    "nonpayable"
  >;

  filters: {};
}
