/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { StudentManagementSystem } from "./StudentManagementSystem";
export * as factories from "./factories";
export { StudentManagementSystem__factory } from "./factories/StudentManagementSystem__factory";
