/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { SchoolManagementSystem__factory } from "./SchoolManagementSystem__factory";
export { Sms__factory } from "./Sms__factory";
