/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { StaffSalaryManager__factory } from "./StaffSalaryManager__factory";
export { StaffSalaryManagerFactory__factory } from "./StaffSalaryManagerFactory__factory";
