/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { SchoolManagementSystem } from "./SchoolManagementSystem";
export type { Sms } from "./Sms";
export * as factories from "./factories";
export { SchoolManagementSystem__factory } from "./factories/SchoolManagementSystem__factory";
export { Sms__factory } from "./factories/Sms__factory";
