/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedListener,
  TypedContractMethod,
} from "./common";

export declare namespace Sms {
  export type StudentStruct = {
    id: BytesLike;
    first_name: string;
    last_name: string;
    age: BigNumberish;
    gender: BigNumberish;
    status: BigNumberish;
  };

  export type StudentStructOutput = [
    id: string,
    first_name: string,
    last_name: string,
    age: bigint,
    gender: bigint,
    status: bigint
  ] & {
    id: string;
    first_name: string;
    last_name: string;
    age: bigint;
    gender: bigint;
    status: bigint;
  };
}

export interface SmsInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "GenderToString"
      | "StatusToString"
      | "addStudent"
      | "deleteStudent"
      | "getAllStudents"
      | "getStudent"
      | "getTotalStudents"
      | "studentList"
      | "updateStudent"
  ): FunctionFragment;

  encodeFunctionData(
    functionFragment: "GenderToString",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "StatusToString",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "addStudent",
    values: [string, string, BigNumberish, BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "deleteStudent",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getAllStudents",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getStudent",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getTotalStudents",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "studentList",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "updateStudent",
    values: [BigNumberish, string, string, BigNumberish, BigNumberish]
  ): string;

  decodeFunctionResult(
    functionFragment: "GenderToString",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "StatusToString",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "addStudent", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "deleteStudent",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getAllStudents",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "getStudent", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getTotalStudents",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "studentList",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "updateStudent",
    data: BytesLike
  ): Result;
}

export interface Sms extends BaseContract {
  connect(runner?: ContractRunner | null): Sms;
  waitForDeployment(): Promise<this>;

  interface: SmsInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  GenderToString: TypedContractMethod<
    [_gender: BigNumberish],
    [string],
    "view"
  >;

  StatusToString: TypedContractMethod<
    [_status: BigNumberish],
    [string],
    "view"
  >;

  addStudent: TypedContractMethod<
    [
      _first_name: string,
      _last_name: string,
      _age: BigNumberish,
      _gender: BigNumberish,
      _status: BigNumberish
    ],
    [void],
    "nonpayable"
  >;

  deleteStudent: TypedContractMethod<
    [_index: BigNumberish],
    [void],
    "nonpayable"
  >;

  getAllStudents: TypedContractMethod<[], [Sms.StudentStructOutput[]], "view">;

  getStudent: TypedContractMethod<
    [_id: BytesLike],
    [[string, string, bigint, string, string]],
    "view"
  >;

  getTotalStudents: TypedContractMethod<[], [bigint], "view">;

  studentList: TypedContractMethod<
    [arg0: BigNumberish],
    [
      [string, string, string, bigint, bigint, bigint] & {
        id: string;
        first_name: string;
        last_name: string;
        age: bigint;
        gender: bigint;
        status: bigint;
      }
    ],
    "view"
  >;

  updateStudent: TypedContractMethod<
    [
      _index: BigNumberish,
      _first_name: string,
      _last_name: string,
      _age: BigNumberish,
      _status: BigNumberish
    ],
    [void],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "GenderToString"
  ): TypedContractMethod<[_gender: BigNumberish], [string], "view">;
  getFunction(
    nameOrSignature: "StatusToString"
  ): TypedContractMethod<[_status: BigNumberish], [string], "view">;
  getFunction(
    nameOrSignature: "addStudent"
  ): TypedContractMethod<
    [
      _first_name: string,
      _last_name: string,
      _age: BigNumberish,
      _gender: BigNumberish,
      _status: BigNumberish
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "deleteStudent"
  ): TypedContractMethod<[_index: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "getAllStudents"
  ): TypedContractMethod<[], [Sms.StudentStructOutput[]], "view">;
  getFunction(
    nameOrSignature: "getStudent"
  ): TypedContractMethod<
    [_id: BytesLike],
    [[string, string, bigint, string, string]],
    "view"
  >;
  getFunction(
    nameOrSignature: "getTotalStudents"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "studentList"
  ): TypedContractMethod<
    [arg0: BigNumberish],
    [
      [string, string, string, bigint, bigint, bigint] & {
        id: string;
        first_name: string;
        last_name: string;
        age: bigint;
        gender: bigint;
        status: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "updateStudent"
  ): TypedContractMethod<
    [
      _index: BigNumberish,
      _first_name: string,
      _last_name: string,
      _age: BigNumberish,
      _status: BigNumberish
    ],
    [void],
    "nonpayable"
  >;

  filters: {};
}
