/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export * as piggyBankSol from "./PiggyBank.sol";
export * as piggyBankFactorySol from "./PiggyBankFactory.sol";
