/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as piggyBankSol from "./PiggyBank.sol";
export type { piggyBankSol };
import type * as piggyBankFactorySol from "./PiggyBankFactory.sol";
export type { piggyBankFactorySol };
export * as factories from "./factories";
export type { IERC20 } from "./PiggyBank.sol/IERC20";
export { IERC20__factory } from "./factories/PiggyBank.sol/IERC20__factory";
export type { PiggyBank } from "./PiggyBank.sol/PiggyBank";
export { PiggyBank__factory } from "./factories/PiggyBank.sol/PiggyBank__factory";
export type { PiggyBankFactory } from "./PiggyBankFactory.sol/PiggyBankFactory";
export { PiggyBankFactory__factory } from "./factories/PiggyBankFactory.sol/PiggyBankFactory__factory";
