/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as contracts from "./contracts";
export type { contracts };
import type * as interfaces from "./interfaces";
export type { interfaces };
export * as factories from "./factories";
export type { SimpleMultisig } from "./contracts/SimpleMultisig";
export { SimpleMultisig__factory } from "./factories/contracts/SimpleMultisig__factory";
export type { SimpleMultisigFactory } from "./contracts/SimpleMultisigFactory";
export { SimpleMultisigFactory__factory } from "./factories/contracts/SimpleMultisigFactory__factory";
export type { ISimpleMultisig } from "./interfaces/ISimpleMultisig";
export { ISimpleMultisig__factory } from "./factories/interfaces/ISimpleMultisig__factory";
