/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Interface, type ContractRunner } from "ethers";
import type {
  IStaffSalaryManager,
  IStaffSalaryManagerInterface,
} from "../../interfaces/IStaffSalaryManager";

const _abi = [
  {
    inputs: [
      {
        internalType: "address",
        name: "_staffAddress",
        type: "address",
      },
      {
        internalType: "string",
        name: "_name",
        type: "string",
      },
      {
        internalType: "enum IStaffSalaryManager.Status",
        name: "_status",
        type: "uint8",
      },
      {
        internalType: "enum IStaffSalaryManager.Role",
        name: "_role",
        type: "uint8",
      },
    ],
    name: "addStaff",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "_address",
        type: "address",
      },
    ],
    name: "getStaff",
    outputs: [
      {
        components: [
          {
            internalType: "string",
            name: "name",
            type: "string",
          },
          {
            internalType: "uint256",
            name: "salary",
            type: "uint256",
          },
          {
            internalType: "enum IStaffSalaryManager.Status",
            name: "status",
            type: "uint8",
          },
          {
            internalType: "enum IStaffSalaryManager.Role",
            name: "role",
            type: "uint8",
          },
        ],
        internalType: "struct IStaffSalaryManager.Staff",
        name: "",
        type: "tuple",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "getTotalStaffs",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "address payable",
        name: "_staffAddress",
        type: "address",
      },
    ],
    name: "paySalary",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "_address",
        type: "address",
      },
      {
        internalType: "enum IStaffSalaryManager.Status",
        name: "_status",
        type: "uint8",
      },
    ],
    name: "updateStaffStatus",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
] as const;

export class IStaffSalaryManager__factory {
  static readonly abi = _abi;
  static createInterface(): IStaffSalaryManagerInterface {
    return new Interface(_abi) as IStaffSalaryManagerInterface;
  }
  static connect(
    address: string,
    runner?: ContractRunner | null
  ): IStaffSalaryManager {
    return new Contract(
      address,
      _abi,
      runner
    ) as unknown as IStaffSalaryManager;
  }
}
