/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as contracts from "./contracts";
export type { contracts };
import type * as interfaces from "./interfaces";
export type { interfaces };
export * as factories from "./factories";
export type { StaffSalaryManager } from "./contracts/StaffSalaryManager";
export { StaffSalaryManager__factory } from "./factories/contracts/StaffSalaryManager__factory";
export type { StaffSalaryManagerFactory } from "./contracts/StaffSalaryManagerFactory";
export { StaffSalaryManagerFactory__factory } from "./factories/contracts/StaffSalaryManagerFactory__factory";
export type { IStaffSalaryManager } from "./interfaces/IStaffSalaryManager";
export { IStaffSalaryManager__factory } from "./factories/interfaces/IStaffSalaryManager__factory";
